### ISSUE TITLE
vitastor-nfs issue without --forgeground

### ISSUE THREAD

**Issue by 1vnt** [vitalif/vitastor#67] opened 2024-05-23 16:25 UTC
I'm unable to create the NFS mount with vitastor-nfs running in the background. I also have the same issue with the mount subcommand.

If I run it like this:
```
vitastor-nfs start --portmap 0 --port 2049 --pool iso-images --fs isofs --foreground
```
I can mount and use nfs like normal with this. 
Mounted using this command:
`mount localhost:/ /mnt/isos/ -o mountport=2049,port=2049,nfsvers=3,soft,nolock,tcp`

**Comment by vitalif** [comment] 2024-05-26 07:44
Hi, this is probably related to unmount autodetection not working - vitastor-nfs counts incoming connections and exits when the last connection is closed, the idea is that the kernel will only close connection when the mountpoint is unmounted.

Try to run `vitastor-nfs mount` with --foreground 1 and check what it prints...
Or you can run it without foreground by with `--logfile .../log.txt` and check the contents of log.txt after it exits.

**Comment by 1vnt** [comment] 2024-06-30 12:46
That was all I got, nothing more. It seems to freeze somewhere whilst not in foreground

**Comment by vitalif** [comment] 2024-07-15 22:57
OK I think I finally found the cause.
It's caused by some NFS call happening right during daemonize().
Basically a sleep(2); before daemonize(); in nfs_proxy.cpp fixes the issue...
I'll investigate further how to fix it because I still want to first mount and then daemonize, not vice versa, to be able to show mounting status to the user...

**Comment by vitalif** [comment] 2024-08-10 17:12
Hi, I still don't understand this "race condition" or whatever it is. But I worked around it by just closing all NFS connections on daemonize(). It seems that Linux sometimes doesn't inherit the opened connection correctly.

Check out the master branch, it should work now.

**Comment by vitalif** [comment] 2024-08-10 17:18
hm wait a minute I'm not sure again..)

**Comment by vitalif** [comment] 2024-08-10 21:01
Fixed an NFS client cleanup issue, now it should work correctly.

**Closed by vitalif** 2024-08-10 21:01 UTC
